### ISSUE TITLE
Переводчик сообщений DeepL API

### ISSUE THREAD

**Issue by cr1ma** [Em1tSan/NeuroGPT#11]
Я предлагаю добавить функцию встроенного перевода сообщений с помощью сервиса **DeepL API**. Это позволит пользователям легко переводить тексты на разные языки. Функция может работать так: рядом с каждым сообщением будет иконка переводчика, по которой можно нажать и получить перевод на выбранный язык. Также можно включить режим “авто перевод”, который будет автоматически переводить все сообщения на нужный язык.

**Comment by qbrainwave** [comment]
ChatGPT ведь может общаться на нужном языке и переводит свои сообщения вполне неплохо. Почему именно потребность в Deepl?
