### ISSUE TITLE
Инвайты не работают

### ISSUE THREAD

**Issue by Ypdes** [Em1tSan/NeuroGPT#17]
Привет! Инвайт на Химеру сдох, Пюр закрыли доступ. Так что смысл в установке пропадает. Без ГПТ4 остальное так себе

**Comment by NealBelov** [comment]
Сдох не инвайт, а сам сервер Химеры. Их забанили, они создали и настраивают новый.
Инвайт обновлен. PurGPT будут периодически открывать сервер.
Вся оперативная информация в [телеграм чате](https://t.me/neurogen_chat)
