### ISSUE TITLE
Ошибка GPT 4 

### ISSUE THREAD

**Issue by demoh2019** [Em1tSan/NeuroGPT#40]
Ошибка: { "error": { "message": "Incorrect API key provided: sk-xxxxxxxxxxxxxxxxxxxxxxxx1", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" }, "hint": { "discord": "https://discord.daku.works" }}

**Comment by Em1tSan** [comment]
Для доступа к DakuWorks API необходимо получить API ключ в их Discord. Подробнее можно почитать в нашем wiki в разделе **Получение ключей**
