### ISSUE TITLE
Add url subdomain param or env

### ISSUE THREAD

**Issue by DeAlexPesh** [Em1tSan/NeuroGPT#41]
hi.
Can you add param or env for url subfolder

EX: https://domain.com/sub/
for docker-compose
```
  environment:
   - SUBF=/sub
```

**Comment by Em1tSan** [comment]
Can you tell me what it's for?

**Comment by DeAlexPesh** [comment]
> Can you tell me what it's for?

This for to be able to use one second-level domain for different services
Thank you

**Comment by Em1tSan** [comment]
Done: https://github.com/Em1tSan/NeuroGPT/commit/d0f22bd57d76f102322375d56211d3c8d657c089

**Comment by DeAlexPesh** [comment]
> Done: [d0f22bd](https://github.com/Em1tSan/NeuroGPT/commit/d0f22bd57d76f102322375d56211d3c8d657c089)

you are funny...

**Comment by DeAlexPesh** [comment]
see please **url_prefix** in **config.json** onthis project [freegpt](https://github.com/ramonvc/freegpt-webui/tree/main)
