### ISSUE TITLE
Ошибка в работе и в повторном запуске

### ISSUE THREAD

**Issue by egergeorge** [Em1tSan/NeuroGPT#42]
![image](https://github.com/Em1tSan/NeuroGPT/assets/22547906/08e6de90-3450-4c80-b184-a29e583fd42d)

![image](https://github.com/Em1tSan/NeuroGPT/assets/22547906/7b41dfdb-f829-4e4f-ad43-5d2fd7e75de3)
При первоначальном автоматическом запуске интерфейс работал, но моё сообщение не отправлялось.
При повторном запуске start.bat появилась ошибка на картинке

**Comment by Em1tSan** [comment]
Ваш провайдер блокирует ip адрес CloudFlare CDN.

На данный момент отключили его, проблема должна быть  решена.
