### ISSUE TITLE
ModuleNotFoundError: No module named 'fastwsgi'

### ISSUE THREAD

**Issue by DeviantSpace** [Em1tSan/NeuroGPT#46]
После полной переустановки перестала запускаться программа, постоянно выдавая ошибку:

```
"\webui_en.py", line 18, in <module>
    import fastwsgi
ModuleNotFoundError: No module named 'fastwsgi'
```

Повторная переустановка программы, VS, Python, не дало никаких результатов. Также и с portable версией

Все модули устанавливались следуя инструкции

git - все нужные галочки
VS 22 commutiny - все дефолт
python 3.10.11 - все нужные галочки

До переустановки запускалось без проблем. 
Сама переустановка была нужна из-за постоянного пустого ответа нейронки на любой запрос при любой модели

**Comment by nappies** [comment]
Такая же ошибка только при свежей установке portable

**Comment by DeviantSpace** [comment]
После еще нескольких дней и переустановок, portable версия смогла запуститься без этой ошибки

Поэтому у кого такая же проблема пробуйте чистую установку portable
