### ISSUE TITLE
any prompt gives an error: "️Произошла ошибка:Произошла ошибка при получении диалога, пожалуйста, проверьте лог бэкенда"

### ISSUE THREAD

**Issue by bananasss00** [Em1tSan/NeuroGPT#50]
![изображение](https://github.com/Em1tSan/NeuroGPT/assets/30229634/4f36aa6f-e1e1-4a6e-bc40-99e597131e33)
I tried with vpn, incognito mode, clean install from github repository - Nothing changes.

---
[RUS]
пробовал с впн, в режиме инкогнито, чистая установка с репозитория github - Ничего не меняется

**Comment by Em1tSan** [comment]
Попробуйте последний релиз. Так как теперь работа идет через наш внешний API - проблема должна быть решена
