### ISSUE TITLE
Jailbreke

### ISSUE THREAD

**Issue by 0naceH** [Em1tSan/NeuroGPT#51]
how to make jailbreake on Russian ?
Как включить jailbreake на русском языке ? через апи

**Comment by 0naceH** [comment]
python api

**Comment by Em1tSan** [comment]
Вопрос не касается работы самого ПО. Что касается методов - вставьте его в качестве первого сообщения по умолчанию при каждом запросе. Подробнее можно узнать в документации OpenAI
