### ISSUE TITLE
Не работает (выходит ошибка) 

### ISSUE THREAD

**Issue by Flooorick** [Em1tSan/NeuroGPT#55]
При написании любого запроса выдаёт ошибку network error (версия на Андроид)
Ps: Мб ошибка на 3.5 и 4

**Comment by Em1tSan** [comment]
Поддержка Andoid прекращена. Воспользуйтесь сторонними клиентами с поддержкой замены API адреса либо нашим онлайн чатом https://chat.neuroapi.host
