### ISSUE TITLE
После технических работ вообще ни один чат не работает

### ISSUE THREAD

**Issue by DeAlexPesh** [Em1tSan/NeuroGPT#58]
выдают китайское "лимит закончился" или:
`Ошибка: {"Error":"An error occurred while generating the response: list index out of range. Please try again later."}`

**Comment by Em1tSan** [comment]
При возникновении подобного рода ошибок, попробуйте вернуться позже и повторить ваш запрос повторно. На данный момент все модели gpt-3.5 работают
