### ISSUE TITLE
No active provider found for the model 

### ISSUE THREAD

**Issue by User1231300** [Em1tSan/NeuroGPT#62]
I installed from the portable version. I get this error when trying to use gpt4.

Ошибка: {"Error":"No active provider found for the model | \u041d\u0430 \u0442\u0435\u043a\u0443\u0449\u0438\u0439 \u043c\u043e\u043c\u0435\u043d\u0442, \u043d\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0438\u0445 \u043f\u0440\u043e\u0432\u0430\u0439\u0434\u0435\u0440\u043e\u0432 \u0434\u043b\u044f \u0434\u0430\u043d\u043d\u043e\u0439 \u043c\u043e\u0434\u0435\u043b\u0438"}  

how to fix?

**Comment by Em1tSan** [comment]
This message means that there are currently no active providers serving this model. They will be available as soon as possible, there is never a definite deadline.
