### ISSUE TITLE
Не работает Api portable.

### ISSUE THREAD

**Issue by 0naceH** [Em1tSan/NeuroGPT#65]
Здравствуйте, все работало, а сейчас перестало работать api.
WebGui работает прекрасно(только 3.5 turbo) а api вообще не какое не работает! (раньше работало нечего не менял)
у вас что-то поменялось ? За два дня api 1 раз сработало на gpt-3.5-turbo-0613...

**Comment by Saltant** [comment]
Шляпа нерабочая, ваще 0 рабочих апи в сборке /clown.jpeg
