### ISSUE TITLE
Docker: не все модели

### ISSUE THREAD

**Issue by pazakharov** [Em1tSan/NeuroGPT#7]
В readme анонсировано:

- ChatGPT-3.5-Turbo
- ChatGPT-3.5-Turbo-16K
- GPT-4 (Нужен ключ ChimeraAPI)
- Sage (Нужен ключ ChimeraAPI)
- Claude Instant (Нужен ключ ChimeraAPI)
- Claude Instant 100K (Нужен ключ ChimeraAPI)
- Claude 2 (Нужен ключ ChimeraAPI)

по факту при запуске в докере : 
- ChatGPT-3.5-Turbo
- ChatGPT-3.5-Turbo-16K
- GPT-4 (Нужен ключ ChimeraAPI)

Но работает только **ChatGPT-3.5-Turbo** (не каждый раз , часто выдает ошибку g4f.Provider.Providers.Acytoo не работает. Пожалуйста, отправьте ваш запрос заново, чтобы он переадресовался новому провайдеру. )
При выборе **ChatGPT-3.5-Turbo-16K или GPT-4 (Нужен ключ ChimeraAPI)** не работает ничего, в логе докера ошибка: 
`Exception: <!doctype html><html lang=en><title>500 Internal Server Error</title><h1>Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`
Можно ли запустить через докер с полным функционалом? (docker WSL, win 11)

**Comment by upais** [comment]
Может вы какой-то не тот контейнер собрали? У меня в докере как раз первый список моделей

**Comment by pazakharov** [comment]
После сегодняшнего обновления вообще перестало запускаться в докере. 
``` [+] Running 1/0
 ✔ Container neurogpt-neurogengpt-1  Created                                                                                                                                              0.0s 
Attaching to neurogpt-neurogengpt-1
neurogpt-neurogengpt-1  | Traceback (most recent call last):
neurogpt-neurogengpt-1  |   File "/app/webui.py", line 25, in <module>
neurogpt-neurogengpt-1  |     import g4f
neurogpt-neurogengpt-1  |   File "/app/g4f/__init__.py", line 3, in <module>
neurogpt-neurogengpt-1  |     from g4f.models import Model, ModelUtils
neurogpt-neurogengpt-1  |   File "/app/g4f/models.py", line 6, in <module>
neurogpt-neurogengpt-1  |     class Model:
neurogpt-neurogengpt-1  |   File "/app/g4f/models.py", line 12, in Model
neurogpt-neurogengpt-1  |     class gpt_35_turbo:
neurogpt-neurogengpt-1  |   File "/app/g4f/models.py", line 22, in gpt_35_turbo
neurogpt-neurogengpt-1  |     status_response = get_status_response()
neurogpt-neurogengpt-1  | TypeError: 'staticmethod' object is not callable
neurogpt-neurogengpt-1 exited with code 1

**Comment by upais** [comment]
Аналогично. Такая же ошибка
