### ISSUE TITLE
Ошибка: ‘choices’

### ISSUE THREAD

**Issue by Rodion1337** [Em1tSan/NeuroGPT#71]
При попытке запроса выдает ошибку: Ошибка: ‘choices’
![Снимок экрана от 2023-11-26 02-48-51](https://github.com/Em1tSan/NeuroGPT/assets/43860793/00524412-125b-4004-af83-db1fe25df59b)

**Comment by pykvarz** [comment]
При попытке запроса выдает ошибку: Ошибка: ‘choices’

**Comment by Rodion1337** [comment]
> @Rodion1337 какая у вас версия чата?

В файле version.txt указано 3.11.4

**Comment by Rodion1337** [comment]
@Em1tSan, в браузере пишет:
NeuroGPT 1.6.1
Python 3.10.12
Gradio 3.36.1
ChuanhuChat 48fad13

**Comment by ForesterGoGo** [comment]
Аналогичная проблема. запуск по start_portable_webui.bat.
Python: 3.11.4
Gradio: 3.36.1
ChuanhuChat: ab0f990

**Comment by AntonChernyshev** [comment]
Проблема в том, что нужно иметь токен, что б пользоваться
В ответе от сервера 'message': 'Invalid token (request id: 20231128132408175691413gZGOpitb)'
Бесплатная модель только с подписью Неуро - все остальне за БАБОС

**Comment by ForesterGoGo** [comment]
Понимаю что в этом уже смысла нет, но хотелось бы чисто для развития осознать.
Правильно что в NeuroGPT 1.6.1 в списках моделей не было бесплатной модели (с припиской Неуро)? 
Т.е. чтобы выбрать бесплатную модель, надо было лезть в другие настройки?
![image](https://github.com/Em1tSan/NeuroGPT/assets/17512198/b32b37b4-a292-4c56-8e79-1d2100b5982a)
